version: "3.8"
services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379

  minio:
    image: minio/minio:latest
    ports:
      - "9001:9001"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PRIVATE_BUCKET: ${MINIO_PRIVATE_BUCKET}
    command: server -console-address :9090 --address :9001 /data
    volumes:
      - minio_storage:/data

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    environment:
      MEILI_ALLOW_UPTO_MB: ${MEILI_ALLOW_UPTO_MB}
      MEILI_HEALTH_PASSWORD: ${MEILI_HEALTH_PASSWORD}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - meilisearch-data:/data

volumes:
  minio_storage: {}
  meilisearch-data: