version: "3.8"
services:
  postgres:
    image: postgres:10.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis
    ports:
      - "6379:6379"
    expose:
      - 6379

  minio:
    image: bitnami/minio
    ports:
      - "5000:5000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_PRIVATE_BUCKET: ${MINIO_PRIVATE_BUCKET}
    volumes:
      - minio-data:/bitnami

volumes:
  minio-data: